version: '3'

services:
    mymuse:
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - 8080:8080
        tty: true
        image: kyoungnam/museprojectsss
        platform: linux/amd64