version: '3'
services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes: 
      - .:/srv #현재 위치와 /srv(django 어플리케이션이 있는 위치) 
      - ./nginx_django:/etc/nginx/conf.d #nginx 설정파일이 있는 위치
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - muse

  muse:
    container_name: muse
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        STAGE: DEV
    volumes: #디렉토리 연결
      - ./MuseDjango:/srv/MuseDjango/
    ports:
      - "8000:8000"
    tty: true
    platform: linux/amd64 # mac M1 local 에서만
    depends_on:
      - redis
    
  celery:
    container_name: celery
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        STAGE: DEV
    tty: true
    volumes:
      - ./MuseDjango:/srv/MuseDjango/
    command:
      - celery
  
  celerybeat:
    container_name: celerybeat
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        STAGE: DEV
    tty: true
    volumes:
      - ./MuseDjango:/srv/MuseDjango/
    command:
      - celerybeat