version: '3'

services:
    muse:
        build:
            image: kyoungnam/musedev
            context: .
            dockerfile: ./Dockerfile
            args:
                STAGE: DEV
        ports:
            - 8080:8080
        tty: true
        platform: linux/amd64